config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    root to: "devise/sessions#new"
  end

  get 'users/main' => 'users#index'
  get 'user' => 'users#show'
  get 'users/all' => 'users#all'
  post 'update_user' => 'users#update'

  get 'create_issue' => 'issues#create'
  post 'create_issue' => 'issues#create'

  get 'issue' => 'issues#show'

  get 'to_work' => 'issues#to_work'
  get 'to_later' => 'issues#to_later'
  get 'to_cancel' => 'issues#to_cancel'
  get 'to_close' => 'issues#to_close'

  get 'supports/main' => 'supports#index'
  get 'supports/issues' => 'supports#issues'
  get 'supports/dashboard' => 'supports#dashboard'

  get 'supports/update_issue_status' => 'supports#update_issue_status'
  get 'supports/update_issue_priority' => 'supports#update_issue_priority'
  get 'supports/update_issue_classification' => 'supports#update_issue_classification'
  get 'find_issue' => 'supports#find_issue'

  get 'supports/show_panel' => 'supports#show_panel'
  get 'supports/show_comment' => 'supports#show_comment'
  get 'supports/comments' => 'supports#comments'

  get 'admins/categories' => 'admins#categories'
  get 'admins/response_time' => 'admins#response_time'
  post 'set_response_time' => 'admins#set_response_time'

  post 'categories_create' => 'categories#create'
  post 'categories_update' => 'categories#update'
  get 'categories_destroy' => 'categories#destroy'

  get 'create_comment' => 'comments#create_comment'
  post 'create_comment' => 'comments#create_comment'
  get 'comments_readed' => 'comments#readed'
  get 'count_unread' => 'comments#count_unread'
  get 'count_specific_unread' => 'comments#count_specific_unread'

  get 'test' => 'supports#test'

  post 'create_attachment' => 'attachments#create'

  get 'user_notifications' => 'notifications#user_notifications'
  get 'mark_as_readed' => 'notifications#mark_as_readed'

end

app/views/admins/_table.html.erb

<table class="table no-border" id="issueTable">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Создал</th>
    <th scope="col">Тема</th>
    <th scope="col">Описание</th>
    <th scope="col">Cоздана</th>
    <th scope="col">Назначена</th>
    <th scope="col">Статус</th>
    <th scope="col"></th>


  </tr>
  </thead>
  <tbody id="issueAll">

  <% issues.each do |issue| %>

      <% unless issue.owner %>

          <tr data-id="<%=issue.id%>">
            <td><%=link_to issue.id, issue_path(id: issue.id), method: :get%></td>
            <td><%= link_to issue.author.username, user_path(id: issue.author.id), method: :get%></td>
            <td><%= link_to truncate(issue.subject, length: 32), issue_path(id: issue.id), method: :get %></td>
            <td class="bodyText" style="padding-top: 1.573rem">
              <%=issue.body ? truncate(issue.body, length: 30) : 'Нету'%>

            </td>
            <td><%= l(issue.created_at, format: "%e %b %Y %H:%M")%></td>
            <td><%= issue.owner ? link_to(issue.owner.username, user_path(id: issue.owner.id), method: :get) : 'Нету'%></td>
            <td><%=issue.status%></td>


            <% if issue.status == 'Новая' %>
                <td>
                  <%= link_to to_work_path(id: issue.id), remote: :true, class: 'btn btn-sm custom-button-blue' do %>
                      В работу
                  <% end %>
                </td>
            <% else %>
                <td>
                  <%= link_to to_later_path(id: issue.id), remote: :true, class: 'btn btn-sm custom-button-yellow' do %>
                      Отложить
                  <% end %>

                  <%= link_to to_close_path(id: issue.id), remote: :true, class: 'btn btn-sm custom-button-green' do %>
                      Выполнена
                  <% end %>
                  <%= link_to to_cancel_path(id: issue.id), remote: :true, class: 'btn btn-sm custom-button-red' do %>
                      Отмена
                  <% end %>
                </td>
            <% end %>


          </tr>
      <% end %>

  <% end %>
  </tbody>
</table>

<script>
    $(document).ready(function() {
        $('#issueTable').dataTable({
            "autoWidth": false,
            pagingType: 'simple_numbers',
            scrollCollapse: false,
            /*            processing: true,*/
            "responsive": false,
            "info": true,
            "ordering": true,
            "bPaginate": true,
            "bStateSave": true,
            "fnStateSave": function (oSettings, oData) {
                localStorage.setItem('offersDataTables', JSON.stringify(oData));
            },
            "fnStateLoad": function (oSettings) {
                return JSON.parse(localStorage.getItem('offersDataTables'));

            },

            "columnDefs": [{
                "targets": [7],
                "orderable": false
            }],

            "language": {
                "sProcessing": "Подождите...",
                "sLengthMenu": "Показать _MENU_ записей",
                "sZeroRecords": "Записи отсутствуют.",
                "sEmptyTable": "В таблице отсутствуют данные",
                "sInfo": "Записи с _START_ до _END_ из _TOTAL_ записей",
                "sInfoEmpty": "Записи с 0 до 0 из 0 записей",
                "sInfoFiltered": "(отфильтровано из _MAX_ записей)",
                "sInfoPostFix": "",
                "sSearch": "",
                "sUrl": "",
                "searchPlaceholder": "Поиск...",
                "sInfoThousands": ",",
                "sLoadingRecords": "Загрузка записей...",
                "oPaginate": {
                    "sFirst": "Первая",
                    "sLast": "Последняя",
                    "sNext": "Следующая",
                    "sPrevious": "Предыдущая"
                },
                "oAria": {
                    "sSortAscending": ": активировать для сортировки столбца по возрастанию",
                    "sSortDescending": ": активировать для сортировки столбца по убыванию"
                }
            }

        });


        $('.row').addClass("table-label");
        $('.dataTables_filter input').addClass('pull-right');

        $('.bodyText').each(function () {
            str = $(this).text()
            html = $.parseHTML(str)
            $(this).html(html)
        })
    });
</script>

app/views/admins/categories.html.erb
<div class="wrapper">

  <%= render 'layouts/left_navbar' %>
  <!-- Page Content  -->
  <div id="content" style="overflow-y: scroll; width: 100%">

    <%= render 'layouts/navbar' %>
    <div class="container-fluid">

      <div class="row" style="margin-top: 35px; margin-left: 5px; margin-right: 5px">
        <div class="col-12">
          <div class="card">

            <div class="card-header real-blue">
              <h5>Категории заявок</h5>
              <span style="color: rgba(255,255,255,.62); font-size: .875rem;">Добавить/удалить категорию и установить баллы</span>
            </div>

            <%= form_tag categories_create_path, method: :post do %>
                <div class="form-inline" style="margin-top: 25px">
                <label class="mr-sm-2" for="inlinenameinput">Название категории:</label>
                <%= text_field_tag :name, nil, class: 'form-control form-control-sm mb-2 mr-sm-2 mb-sm-0',
                                   style: 'border: 1px solid #a9a9a9', id: 'inlinenameinput' %>

                  <label class="mr-sm-2" for="inlinetime">Допустимое время:</label>
                  <input type="text" name="per_time" class="form-control form-control-sm mb-2 mr-sm-2 mb-sm-0"
                         value='00:00' style="width: 10%; min-width: 70px" id="inlinetime">

                <label class="mr-sm-2" for="inlinenumberinput">Баллы:</label>
                <input class="form-control form-control-sm mb-2 mr-sm-2 mb-sm-0" name="rate"
                       type="number" id="inlinenumberinput" style="width: 10%; min-width: 70px">

                <%= button_tag(type: "submit", class: "btn btn-sm custom-button-blue mb-1 ml-1") do %>
                    <i class="fa fa-check" aria-hidden="true"></i>
                      Добавить
                <% end %>

                </div>
            <% end %>

            <hr>
            <h5 style="padding-bottom: 15px">Текущие категории:</h5>
            <table class="table no-border" id="categoriesTable">
              <thead>
              <tr class="row" style="margin-left: 1px">
                <th class="col-4">Название</th>
                <th class="col-1">Допустимое время</th>
                <th class="col-1">Балы</th>
                <th class="col-4"></th>
              </tr>
              </thead>
              <tbody>
                <% @categories.each do |cs| %>
                  <tr class="row" style="margin-left: 1px">
                    <%= form_tag  categories_update_path, method: :post do %>
                      <td class="col-4"><%= text_field_tag :name, nil, placeholder: cs.name, class: 'form-control'%></td>
                      <td class="col-1">
                        <div class="input-group" id="clockpicker<%=cs.id%>">
                          <input type="text" name="per_time" class="form-control"
                                 value=<%= cs.permissible_time ? time_conversion(cs.permissible_time) : '00:00' %>>
                          <span class="input-group-addon">
                          <span class="glyphicon glyphicon-time"></span>
                        </span>
                        </div>
                        <script type="text/javascript">
                            $('#clockpicker<%=cs.id%>').clockpicker({
                                placement: 'top',
                                donetext: 'Готово'
                            });
                        </script>
                      </td>
                      <td class="col-1"><%= text_field_tag :rate, nil, placeholder: cs.rate ? cs.rate : '0',
                                             class: 'form-control' %></td>
                      <td class="col-4">
                        <%= hidden_field_tag :id, cs.id %>
                        <%= button_tag(type: "submit", class: "btn btn-sm custom-button-blue") do %>
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            Редактировать
                        <% end %>
                    <% end %>
                      <%= link_to categories_destroy_path(id: cs.id),
                                  class: 'btn btn-sm custom-button-red' do %>
                          <i class="fa fa-close" aria-hidden="true"></i>
                          Удалить
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>

    $(document).ready(function() {

        $('#inlinetime').clockpicker({
            donetext: 'Готово'
        });

        $(".editCs").each(function() {
            $(this).on('click', function (e) {

            });
        });

        $('#categoriesTable').dataTable({
            "autoWidth": false,
            pagingType: 'simple_numbers',
            scrollCollapse: false,
            /*            processing: true,*/
            "responsive": false,
            "info": true,
            "ordering": false,
            "bPaginate": true,
            "bStateSave": true,
            "fnStateSave": function (oSettings, oData) {
                localStorage.setItem('offersDataTables', JSON.stringify(oData));
            },
            "fnStateLoad": function (oSettings) {
                return JSON.parse(localStorage.getItem('offersDataTables'));

            },

            "columnDefs": [{
                "targets": [0, 3],
                "orderable": false
            }],

            "language": {
                "sProcessing": "Подождите...",
                "sLengthMenu": "Показать _MENU_ записей",
                "sZeroRecords": "Записи отсутствуют.",
                "sEmptyTable": "В таблице отсутствуют данные",
                "sInfo": "Записи с _START_ до _END_ из _TOTAL_ записей",
                "sInfoEmpty": "Записи с 0 до 0 из 0 записей",
                "sInfoFiltered": "(отфильтровано из _MAX_ записей)",
                "sInfoPostFix": "",
                "sSearch": "",
                "sUrl": "",
                "searchPlaceholder": "Поиск...",
                "sInfoThousands": ",",
                "sLoadingRecords": "Загрузка записей...",
                "oPaginate": {
                    "sFirst": "Первая",
                    "sLast": "Последняя",
                    "sNext": "Следующая",
                    "sPrevious": "Предыдущая"
                },
                "oAria": {
                    "sSortAscending": ": активировать для сортировки столбца по возрастанию",
                    "sSortDescending": ": активировать для сортировки столбца по убыванию"
                }
            }

        });

        $('.dataTables_filter input').css('display', 'none');
    });
</script>

app/views/admins/index.html.erb
<div class="wrapper">
  <!-- Sidebar  -->
  <nav id="sidebar">
    <div class="sidebar-header">
      <h3>Postdesk</h3>
      <strong>PD</strong>
    </div>

    <ul class="list-unstyled components">
      <li class="active">
        <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
          <i class="fa fa-home"></i>
          <span>Домой</span>
        </a>
        <ul class="collapse list-unstyled" id="homeSubmenu">
          <li>
            <a href="#">Home 1</a>
          </li>
          <li>
            <a href="#">Home 2</a>
          </li>
          <li>
            <a href="#">Home 3</a>
          </li>
        </ul>
      </li>
      <li>
        <a href="#">
          <i class="fa fa-briefcase"></i>
          <span>Home</span>
        </a>
        <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
          <i class="fa fa-copy"></i>
          <span>Home</span>
        </a>
        <ul class="collapse list-unstyled" id="pageSubmenu">
          <li>
            <a href="#">Page 1</a>
          </li>
          <li>
            <a href="#">Page 2</a>
          </li>
          <li>
            <a href="#">Page 3</a>
          </li>
        </ul>
      </li>
    </ul>

  </nav>

  <!-- Page Content  -->
  <div id="content" style="overflow-y: scroll; width: 100%">

    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background: transparent !important;">
      <div class="container-fluid">

        <button type="button" id="sidebarCollapse" class="btn btn-toggle">
          <i id="toggleIcon" class="fa fa-ellipsis-v"></i>
        </button>
        <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>



        <div class="collapse navbar-collapse" id="navbarSupportedContent">

          <ul class="nav navbar-nav" style="margin-left: 50px">
            <li class="nav-item">
              <a class="nav-link bread" href="#">Домой</a>
            </li>
          </ul>

          <ul class="nav navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Page</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Page</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Page</a>
            </li>
            <li class="nav-item">

            </li>
          </ul>
        </div>
      </div>
    </nav>


    <div class="container-fluid">
      <div class="row" style="margin-top: 50px; margin-left: 5px">
        <div class="col-5">
          <div class="card">
            <h5>Создать задачу:</h5>
            <br>


          </div>
        </div>

        <div class="col-3">

        </div>

      </div>

    </div>

  </div>
</div>

<script>
    $( "#test" ).select2({
        language: "ru-RU",

    });

</script>

<%= subscribe_to "/issues/count" %>

app/views/admins/response_time.html.erb
<div class="wrapper">

  <%= render 'layouts/left_navbar' %>
  <!-- Page Content  -->
  <div id="content" style="overflow-y: scroll; width: 100%">

    <%= render 'layouts/navbar' %>
    <div class="container-fluid">

      <div class="row" style="margin-top: 35px; margin-left: 5px; margin-right: 5px">
        <div class="col-12">
          <div class="card">

            <div class="card-header real-blue">
              <h5>Время реагирования</h5>
              <span style="color: rgba(255,255,255,.62); font-size: .875rem;">Установить время реагирования на заявку</span>
            </div>

            <%= form_tag set_response_time_path, method: :post do %>
                <div class="form-inline" style="margin-top: 25px">
                  <label class="mr-sm-2" for="inlinenameinput">Время реагирования:</label>
                  <%= text_field_tag :minutes, nil, class: 'form-control form-control-sm mb-2 mr-sm-2 mb-sm-0',
                                     style: 'border: 1px solid #a9a9a9', id: 'inlinenameinput',
                                     placeholder: 'сейчас: '+@current %>
                  <span>минут</span>
                  <%= button_tag(type: "submit", class: "btn btn-sm custom-button-blue mb-1 ml-1") do %>
                      <i class="fa fa-check" aria-hidden="true"></i>
                      Установить
                  <% end %>
                </div>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>
