config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    root to: "devise/sessions#new"
  end

  get 'users/main' => 'users#index'
  get 'user' => 'users#show'
  get 'users/all' => 'users#all'
  post 'update_user' => 'users#update'

  get 'create_issue' => 'issues#create'
  post 'create_issue' => 'issues#create'

  get 'issue' => 'issues#show'

  get 'to_work' => 'issues#to_work'
  get 'to_later' => 'issues#to_later'
  get 'to_cancel' => 'issues#to_cancel'
  get 'to_close' => 'issues#to_close'

  get 'supports/main' => 'supports#index'
  get 'supports/issues' => 'supports#issues'
  get 'supports/dashboard' => 'supports#dashboard'

  get 'supports/update_issue_status' => 'supports#update_issue_status'
  get 'supports/update_issue_priority' => 'supports#update_issue_priority'
  get 'supports/update_issue_classification' => 'supports#update_issue_classification'
  get 'find_issue' => 'supports#find_issue'

  get 'supports/show_panel' => 'supports#show_panel'
  get 'supports/show_comment' => 'supports#show_comment'
  get 'supports/comments' => 'supports#comments'

  get 'admins/categories' => 'admins#categories'
  get 'admins/response_time' => 'admins#response_time'
  post 'set_response_time' => 'admins#set_response_time'

  post 'categories_create' => 'categories#create'
  post 'categories_update' => 'categories#update'
  get 'categories_destroy' => 'categories#destroy'

  get 'create_comment' => 'comments#create_comment'
  post 'create_comment' => 'comments#create_comment'
  get 'comments_readed' => 'comments#readed'
  get 'count_unread' => 'comments#count_unread'
  get 'count_specific_unread' => 'comments#count_specific_unread'

  get 'test' => 'supports#test'

  post 'create_attachment' => 'attachments#create'

  get 'user_notifications' => 'notifications#user_notifications'
  get 'mark_as_readed' => 'notifications#mark_as_readed'

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :owner, :class_name => 'User'
  belongs_to :author, :class_name => 'User'
  has_many :histories
  belongs_to :category
  has_many :comments
  has_many :notifications

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController

  def create
    @issue = Issue.create issue_params
    issue_create_history(@issue.author.id, @issue.id)
=begin
    if params[:file]
      create_attachment(params[:file], @issue.id)
    end
=end
    @supports = get_supports
    @issues = Issue.all
    @response_time = AdminSetting.first.response_time
    @my_issues = Issue.where(author_id: current_user.id)
    respond_to do |format|
      format.js
    end

  end

  def show
    @issue = Issue.find(params[:id])
    @comments = Comment.where(issue_id: @issue.id)
  end

  def to_work
    @issue = Issue.find(params[:id])
    @issue.update(owner: current_user, status: 'В работе', open_at: Time.now)
    issue_get_to_work_history(current_user.id, @issue.id)
    create_notification_to_owner(@issue.id)
    create_notification_to_author(@issue.id)
    @response_time = AdminSetting.first.response_time
    @issues = Issue.all
    @recepients = [@issue.author.id, @issue.owner.id]
    @supports = get_supports
    respond_to do |format|
      format.js
    end
  end

  private

  def issue_create_history(user_id, issue_id)
    History.create(event: 'Cоздана', user_id: user_id, issue_id: issue_id)
  end

  def issue_get_to_work_history(user_id, issue_id)
    History.create(event: 'Взята в работу', user_id: user_id, issue_id: issue_id)
  end

  def create_notification_to_owner(issue_id)
    issue = Issue.find(issue_id)
    Notification.create(event: "Заявка №#{issue.id} взята в работу", user_id: issue.owner.id, issue_id: issue.id)
  end

  def create_notification_to_author(issue_id)
    issue = Issue.find(issue_id)
    Notification.create(event: "Заявка №#{issue.id} взята в работу", user_id: issue.author.id, issue_id: issue.id)
  end

  def get_supports
    test = User.where(group: ['support', 'admin'])
    test.ids
  end

  def issue_params
    params.permit(:subject, :body, :category_id).merge(author: current_user, status: 'Новая', priority: 'Обычный')
  end

  def create_attachment(file, issue_id)
    p params
    @icon = Attachment.new(document: file, issue_id: issue_id)
    if @icon.save!
      respond_to do |format|
        format.json{ render :json => @icon }
      end
    end
  end

end

app/views/issues/_issue.html.erb
<a data-id="<%=issue.id%>" href="URL" class="commentsUrl">

  <div class="row no-gutters" style="border-top: 1px solid rgba(0, 0, 0, 0.1); padding: 0.5rem">

    <div class="col-auto">
      <img src="<%=issue.author.avatar.url%>" class="img-fluid" width="42" height="42">
    </div>
    <div class="col">
      <div class="pl-2">
        <sup class="float-right pr-2 mt-3">
          <%=(time_ago_in_words(issue.comments.last.created_at)).gsub('около', '') + ' назад'%>
        </sup>
        <h6 class="card-title mb-0"><%=issue.author.username%></h6>
        <p class="card-text"><%=issue.subject%></p>
      </div>
    </div>
  </div>
  <p style="margin-left: 28px; border-left: 2px solid red"><%=issue.comments.last.body if issue.comments.any?%></p>
</a>

app/views/issues/_stats.html.erb
<div class="row row-eq-height" style="margin-top: 35px; margin-left: 5px; margin-right: 5px;
    background: transparent;
    box-shadow: none">
  <div class="col-3 col-xs-6">
    <div class="card" style="border-top: 0; width: 100%; height: 100%">
      <div class="card-icon-container green text-center">
        <i class="fa fa-check card-icon" style="margin-top: 20px"></i>
      </div>
      <span class="ml-auto" style="margin-top: -50px; color: #999;">Выполнено</span>
      <h3 class="ml-auto">44</h3>
      <hr>
      <p class="text-center" style="color: #999; font-size: 12px;">
        За месяц <b style="color:green">43%</b><i class="fa fa-arrow-up" style="color:green"></i>
      </p>
    </div>
  </div>
  <div class="col-3">
    <div class="card" style="border-top: 0; width: 100%; height: 100%">
      <div class="card-icon-container blue text-center">
        <i class="fa fa-cogs card-icon" style="margin-top: 20px"></i>
      </div>
      <span class="ml-auto" style="margin-top: -50px; color: #999;">В работе</span>
      <h3 class="ml-auto">76</h3>
      <hr>
      <p class="text-center" style="color: #999; font-size: 12px;">
        За месяц <b style="color:red">33%</b><i class="fa fa-arrow-down" style="color:red"></i>
      </p>
    </div>
  </div>
  <div class="col-3">
    <div class="card" style="border-top: 0; width: 100%; height: 100%">
      <div class="card-icon-container orange text-center">
        <i class="fa fa-clock-o card-icon" style="margin-top: 20px"></i>
      </div>
      <span class="ml-auto" style="margin-top: -50px; color: #999;">Отложено</span>
      <h3 class="ml-auto">50</h3>
      <hr>
      <p class="text-center" style="color: #999; font-size: 12px;">
        За месяц <b style="color:green">39%</b><i class="fa fa-arrow-up" style="color:green"></i>
      </p>
    </div>
  </div>
  <div class="col-3">
    <div class="card" style="border-top: 0; width: 100%; height: 100%">
      <div class="card-icon-container red text-center">
        <i class="fa fa-times card-icon" style="margin-top: 20px"></i>
      </div>
      <span class="ml-auto" style="margin-top: -50px; color: #999;">Отменено</span>
      <h3 class="ml-auto">12</h3>
      <hr>
      <p class="text-center" style="color: #999; font-size: 12px;">
        За месяц <b style="color:green">73%</b><i class="fa fa-arrow-up" style="color:green"></i>
      </p>
    </div>
  </div>
</div>

<div class="row" style="margin-top: 25px; margin-left: 5px; margin-right: 5px;">
    <div class="col-6">
      <div class="card" style="border-top: 0; width: 100%; height: 100%">
      <canvas id="myChart" height="250"></canvas>
      </div>
    </div>

  <div class="col-6">
    <div class="card" style="border-top: 0; width: 100%; height: 100%">
    <canvas id="line-chart" height="250"></canvas>
    </div>
  </div>

  <div class="col-12">

  </div>

</div>


<script>


    var ctx = document.getElementById('myChart');
    var myChart = new Chart(ctx, {
        type: 'doughnut',
        data: {
            labels: ['Отменено', 'В работе', 'Выполнено', 'Отложено'],
            datasets: [{
                label: '# of Votes',
                data: [12, 19, 5, 3],
                backgroundColor: [
                    '#ef5350',
                    '#26c6da',
                    '#66bb6a',

                    '#ffa726'
                ],
                borderColor: [
                    '#ef5350',
                    '#26c6da',
                    '#66bb6a',

                    '#ffa726'
                ],
                borderWidth: 1
            }]
        },
        options: {
        }
    });

    new Chart(document.getElementById("line-chart"), {
        type: 'line',
        data: {
            labels: [1500,1600,1700,1750,1800,1850,1900,1950,1999,2050],
            datasets: [{
                data: [86,114,106,106,107,111,133,221,783,2478],
                label: "В работе",
                backgroundColor: "#26c6da",
                borderColor: "#26c6da",
                fill: false
            }, {
                data: [282,350,411,502,635,809,947,1402,3700,5267],
                label: "Отменено",
                backgroundColor: "#ef5350",
                borderColor: "#ef5350",
                fill: false
            }, {
                data: [168,170,178,190,203,276,408,547,675,734],
                label: "Выполнено",
                backgroundColor: "#66bb6a",
                borderColor: "#66bb6a",
                fill: false
            }, {
                data: [40,20,10,16,24,38,74,167,508,784],
                label: "Отложено",
                backgroundColor: "#ffa726",
                borderColor: "#ffa726",
                fill: false
            }
            ],
        },
        options: {
        }
    });

</script>

app/views/issues/create.js.erb
$.amaran({
    'theme'     :'awesome ok',
    'content'   :{
        title:'Успех!',
        message:'Задача успешно создана!',
        info:'',
        icon:'fa fa-check-square-o'
    },
    'position'  :'bottom right',
    'outEffect' :'slideBottom'
});

$('#myIssues').html("<%= j render(:partial => '/users/my_issues', :locals => {my_issues: @my_issues}) %>")

$( '#issueForm' ).each(function(){
    this.reset();
});

<% @supports.each do |sup_id| %>
  <% publish_to "/issues/all/#{sup_id}" do %>
    $('#issues').html("<%= j render(:partial => '/supports/all_issues', :locals => {issues: @issues, response_time: @response_time}) %>")
  <% end %>
<% end %>


app/views/issues/show.html.erb
<div class="wrapper">

  <%= render 'layouts/left_navbar' %>
  <!-- Page Content  -->
  <div id="content" style="overflow-y: scroll; width: 100%">

    <%= render 'layouts/navbar' %>
    <div class="container-fluid">

      <div class="row" style="margin-top: 35px; margin-left: 5px; margin-right: 5px; margin-bottom: 25px">
        <div class="col-12">
          <div class="card">

            <div class="card-header real-blue">
              <h5>Заявка №<%=@issue.id%></h5>
              <span style="color: rgba(255,255,255,.62); font-size: .875rem;">Все обновления заявки тут</span>
            </div>
            <h3 class="mb-0 mt-3"><i class="fa fa-file-o pl-2" aria-hidden="true"></i> <%=@issue.subject%></h3>
            <div class="d-inline p-2 ">Приоритет:
              <% if @issue.priority == 'Низкий'%>
                  <i class="fa fa-circle-o" style="color:#007bff"></i>
              <% elsif @issue.priority == 'Обычный'%>
                  <i class="fa fa-circle-o" style="color:#28a745"></i>
              <% elsif @issue.priority == 'Высокий'%>
                  <i class="fa fa-circle-o" style="color:#fb3"></i>
              <% elsif @issue.priority == 'Немедленный'%>
                  <i class="fa fa-circle-o" style="color:#ff3547"></i>
              <% end %>
              <%=@issue.priority%>
              <span style="padding-left: 15px">Открыта: <i class="fa fa-user-o" aria-hidden="true"></i> <%=@issue.author.username%></span>

              <span style="padding-left: 15px">
                <i class="fa fa-calendar" aria-hidden="true"></i>
                <%=l(@issue.created_at, format: "%e %b %Y")%>
                <i class="fa fa-clock-o" aria-hidden="true"></i>
                <%=l(@issue.created_at, format: "%H:%M")%>
              </span>
            </div>
            <hr>
            <h6 class="p-2">Описание:</h6>

            <div class="row pl-1">
              <div class="col-6">
                <table class="table table-sm table-borderless" style=" ">
                  <tbody>
                  <tr>
                    <td class="w-30 text-secondary">Категория:</td>
                    <td class="w-70"><%=@issue.category.name%></td>
                  </tr>
                  <tr>
                    <td class="w-30 text-secondary">Тема:</td>
                    <td class="w-70"><%=@issue.subject%></td>
                  </tr>
                  <tr>
                    <td class="w-30 text-secondary">Описание:</td>
                    <td class="w-70">
                      <span id="htmlText"><%=truncate(@issue.body, length: 42)%></span>
                    </td>
                  </tr>
                  </tbody>
                </table>
              </div>

              <div class="col-6">
                <table id="priorityTable" class="table table-sm table-borderless" style=" ">
                  <tbody>
                  <tr>
                    <td class="w-30 text-secondary">Статус:</td>
                    <td data-priority="<%=@issue.id%>" class="w-70">
                      <% if @issue.status == 'В работе'%>
                          <span class="badge badge-upper badge-pill badge-primary"><%=@issue.status%></span>
                      <% elsif @issue.status == 'Новая' %>
                          <span class="badge badge-upper badge-pill badge-secondary"><%=@issue.status%></span>
                      <% elsif @issue.status == 'Отложена' %>
                          <span class="badge badge-upper badge-pill badge-warning"><%=@issue.status%></span>
                      <% elsif @issue.status == 'Отменена' %>
                          <span class="badge badge-upper badge-pill badge-danger"><%=@issue.status%></span>
                      <% elsif @issue.status == 'Выполнена' %>
                          <span class="badge badge-upper badge-pill badge-success"><%=@issue.status%></span>
                      <% end %>
                    </td>
                  </tr>
                  <tr>
                    <td class="w-30 text-secondary">Открыта:</td>
                    <td class="w-70">
                      <%=@issue.open_at ? l(@issue.open_at, format: "%e %b %Y %H:%M") : '-'%>
                    </td>
                  </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <h6 class="p-2">Коментарии:</h6>

              <% if @issue.owner == current_user || @issue.author == current_user%>

                <div id="comments">
                  <%= render 'comments/comments', comments: @comments %>
                </div>

                <%= form_tag create_comment_path, method: :post, remote: true do %>
                  <%= text_area_tag(:body, nil, class: 'form-control', rows: 3, id:'body', style: 'resize: none;')%>
                  <%= hidden_field_tag :issue_id, @issue.id %>
                  <%= submit_tag 'Написать', :class => 'btn custom-button-blue mt-2', id: 'submitBtn' %>
                <% end %>

                <%= subscribe_to "/comments/#{@issue.id}" %>
              <% end %>



          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>

    $(document).ready(function() {

        $.ajax({
            url: "<%= comments_readed_path %>",
            type: "GET",
            data: {issue_id: <%=@issue.id%>}
        })


/*            var el = $('#htmlText');
            str = el.text();
            html = $.parseHTML(str);
            el.html(html)*/

    });
</script>


app/views/issues/to_work.js.erb
$.amaran({
    'theme'     :'awesome ok',
    'content'   :{
        title:'Внимание!',
        message:'Подобрал заявку',
        info:'',
        icon:'fa fa-check-square-o'
    },
    'position'  :'bottom right',
    'outEffect' :'slideBottom'
});

<% @supports.each do |sup_id| %>
  <% publish_to "/issues/all/#{sup_id}" do %>
  $('#issues').html("<%= j render(:partial => '/supports/all_issues', :locals => {issues: @issues, response_time: @response_time}) %>")
  <% end %>
<% end %>

<% @recepients.each do |re_id| %>
  <% publish_to "/notifications/#{re_id}" do %>
    $.ajax({
        url: "<%= user_notifications_path %>",
        type: "GET",
        data: {user_id: <%=re_id%>}
    }).done(function(response) {
        var data = response.notifications.msg
        data.forEach(function(element){
            $('#notifications').append(
                '<%=link_to mark_as_readed_path(current_user.id), class: 'dropdown-item' do %>'+
                  element.event+
                '<% end %>'
            )
        });

    });
  <% end %>
<% end %>

<% publish_to "/comments/count/#{current_user.id}" do %>
  $.ajax({
      url: "<%= count_unread_path %>",
      type: "GET"
  }).done(function(response) {
      /*console.log(response.comments.comments)*/
      if (response.comments.counter > 0) {
          $('#unreadCount').text(response.comments.counter);
      }else {
          $('#unreadCount').text('');
      }
  });
<% end %>

<% publish_to "/comments/#{@issue.id}" do %>
$('#priorityTable td').each(function() {
    if ($(this).data("priority")== <%=@issue.id%>) {
        $(this).html(
            '<% if @issue.status == 'В работе'%>'+
            '<span class="badge badge-upper badge-pill badge-primary"><%=@issue.status%></span>'+
            '<% elsif @issue.status == 'Новая' %>'+
            '<span class="badge badge-upper badge-pill badge-secondary"><%=@issue.status%></span>'+
            '<% elsif @issue.status == 'Отложена' %>'+
            '<span class="badge badge-upper badge-pill badge-warning"><%=@issue.status%></span>'+
            '<% elsif @issue.status == 'Отменена' %>'+
            '<span class="badge badge-upper badge-pill badge-danger"><%=@issue.status%></span>'+
            '<% elsif @issue.status == 'Выполнена' %>'+
            '<span class="badge badge-upper badge-pill badge-success"><%=@issue.status%></span>'+
            '<% end %>')
    }
});
<% end %>

<% publish_to "/users/#{@issue.id}" do %>
  $('#myIssueTable td').each(function() {

      if ($(this).data("priority")== <%=@issue.id%>) {
          $(this).html(
              '<% if @issue.status == 'В работе'%>'+
              '<span class="badge badge-upper badge-pill badge-primary"><%=@issue.status%></span>'+
              '<% elsif @issue.status == 'Новая' %>'+
              '<span class="badge badge-upper badge-pill badge-secondary"><%=@issue.status%></span>'+
              '<% elsif @issue.status == 'Отложена' %>'+
              '<span class="badge badge-upper badge-pill badge-warning"><%=@issue.status%></span>'+
              '<% elsif @issue.status == 'Отменена' %>'+
              '<span class="badge badge-upper badge-pill badge-danger"><%=@issue.status%></span>'+
              '<% elsif @issue.status == 'Выполнена' %>'+
              '<span class="badge badge-upper badge-pill badge-success"><%=@issue.status%></span>'+
          '<% end %>')
      }

  });
<% end %>