config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    root to: "devise/sessions#new"
  end

  get 'users/main' => 'users#index'
  get 'user' => 'users#show'
  get 'users/all' => 'users#all'
  post 'update_user' => 'users#update'

  get 'create_issue' => 'issues#create'
  post 'create_issue' => 'issues#create'

  get 'issue' => 'issues#show'

  get 'to_work' => 'issues#to_work'
  get 'to_later' => 'issues#to_later'
  get 'to_cancel' => 'issues#to_cancel'
  get 'to_close' => 'issues#to_close'

  get 'supports/main' => 'supports#index'
  get 'supports/issues' => 'supports#issues'
  get 'supports/dashboard' => 'supports#dashboard'

  get 'supports/update_issue_status' => 'supports#update_issue_status'
  get 'supports/update_issue_priority' => 'supports#update_issue_priority'
  get 'supports/update_issue_classification' => 'supports#update_issue_classification'
  get 'find_issue' => 'supports#find_issue'

  get 'supports/show_panel' => 'supports#show_panel'
  get 'supports/show_comment' => 'supports#show_comment'
  get 'supports/comments' => 'supports#comments'

  get 'admins/categories' => 'admins#categories'
  get 'admins/response_time' => 'admins#response_time'
  post 'set_response_time' => 'admins#set_response_time'

  post 'categories_create' => 'categories#create'
  post 'categories_update' => 'categories#update'
  get 'categories_destroy' => 'categories#destroy'

  get 'create_comment' => 'comments#create_comment'
  post 'create_comment' => 'comments#create_comment'
  get 'comments_readed' => 'comments#readed'
  get 'count_unread' => 'comments#count_unread'
  get 'count_specific_unread' => 'comments#count_specific_unread'

  get 'test' => 'supports#test'

  post 'create_attachment' => 'attachments#create'

  get 'user_notifications' => 'notifications#user_notifications'
  get 'mark_as_readed' => 'notifications#mark_as_readed'

end

app/controllers/supports_controller.rb
class SupportsController < ApplicationController
  def index
    @issues = Issue.all
    @response_time = AdminSetting.first.response_time
  end

  def dashboard

  end

  def test

  end

  def comments
    @issues = Issue.where(owner_id: current_user.id)
  end

  def find_issue
    issue = Issue.find(params[:id])
    open_at = issue.open_at.to_f * 1000
    pt = issue.category.permissible_time
    render :json => {issue: {"open_at":open_at, "pt":pt}}
  end

  def issues
    @issues = Issue.where(owner_id: current_user.id)
  end

  def update_issue_status
    @issue = Issue.find(params["issue_id"])
    if params["status"] == 'Отложена'
      to_wait(@issue)
      issue_to_wait_history(@issue.owner.id, @issue.id)
    elsif params["status"] == 'В работе'
      to_work(@issue)
      issue_to_work_history(@issue.owner.id, @issue.id)
    elsif params["status"] == 'Выполнена'
      to_done(@issue)
      issue_to_done_history(@issue.owner.id, @issue.id)
    end
    @issues = Issue.where(owner_id: current_user.id)
    respond_to do |format|
      format.js
    end
  end

  def to_cancel
    issue = find(["issue_id"])
    issue_to_cancel_history(issue.id, issue.owner.id)
    issue.update(status: 'Новая', owner_id: nil)
  end

  def update_issue_priority
    @issue = Issue.find(params["issue_id"])
    @issue.update(priority: params["priority"])
    issue_change_priority_history(@issue.owner.id, @issue.id, params['priority'])
    @issues = Issue.where(owner_id: current_user.id)
    respond_to do |format|
      format.js
    end
  end

  def update_issue_classification
    @issue = Issue.find(params["issue_id"])
    @issue.update(classification: params["classification"])
    issue_change_cs_history(@issue.owner.id, @issue.id, params["classification"])
    @issues = Issue.where(owner_id: current_user.id)
    respond_to do |format|
      format.js
    end
  end

  def show_panel
    @issue = Issue.find(params["issue_id"])
    respond_to do |format|
      format.js
    end
  end

  def show_comment
    @issue = Issue.find(params["issue_id"])
    respond_to do |format|
      format.js
    end
  end

  private

  def to_wait(issue)
    issue.update(status: 'Отложена')
  end

  def to_work(issue)
    issue.update(status: 'В работе')
  end

  def to_done(issue)
    issue.update(status: 'Выполнена')
  end

  def issue_to_wait_history(user_id, issue_id)
    History.create(event: 'Отложена', user_id: user_id, issue_id: issue_id)
  end

  def issue_to_work_history(user_id, issue_id)
    History.create(event: 'Взята в работу', user_id: user_id, issue_id: issue_id)
  end

  def issue_to_done_history(user_id, issue_id)
    History.create(event: 'Выполнена', user_id: user_id, issue_id: issue_id)

    events = History.all.where(issue_id: issue_id)

    inwork = 0
    delayed = 0
    delayed_start = nil
    inwork_start = nil

    events.each do |ev|
      if ev.event == 'Взята в работу'
        inwork_start = ev.created_at
        if delayed_start
          delayed += ev.created_at - delayed_start
          delayed_start = nil
        end
      end
      if ev.event == 'Отложена'
        delayed_start = ev.created_at
        if inwork_start
          inwork += ev.created_at - inwork_start
          inwork_start = nil
        end
      end
      if ev.event == 'Выполнена'
        if inwork_start
          inwork += ev.created_at - inwork_start
          inwork_start = nil
        end
        if delayed_start
          delayed += ev.created_at - delayed_start
          delayed_start = nil
        end
      end
    end
    p '-------'
    p 'в секундах'
    p delayed
    p inwork

  end

  def issue_to_cancel_history(user_id, issue_id)
    History.create(event: 'Отменена', user_id: user_id, issue_id: issue_id)
  end

  def issue_change_priority_history(user_id, issue_id, priority)
    History.create(event: "Приоритет изменен #{priority}", user_id: user_id, issue_id: issue_id)
  end

  def issue_change_cs_history(user_id, issue_id, classification)
    History.create(event: "Тип изменен #{classification}", user_id: user_id, issue_id: issue_id)
  end

end

app/views/supports/_comments_issues_list.html.erb
<div id="commentsIssuesList">
<% issues.order('updated_at  DESC').try(:each) do |issue| %>
      <% if issue.comments.any? %>
    <a data-id="<%=issue.id%>" href="URL" class="commentsUrl">

      <div class="row no-gutters" style="border-top: 1px solid rgba(0, 0, 0, 0.1); padding: 0.5rem">

        <div class="col-auto">
          <img src="<%=issue.author.avatar.url%>" class="img-fluid" width="42" height="42">
        </div>
        <div class="col">
          <div class="pl-2">
            <sup class="float-right pr-2 mt-3">
              <%=(time_ago_in_words(issue.comments.last.created_at)).gsub('около', '') + ' назад'%>
            </sup>
            <h6 class="card-title mb-0"><%=issue.author.username%></h6>
            <p class="card-text"><%=issue.subject%></p>
          </div>
        </div>
      </div>
      <p style="margin-left: 28px; border-left: 2px solid red"><%=issue.comments.last.body if issue.comments.any?%></p>
    </a>
      <%= subscribe_to "/issuesComments/#{issue.id}" %>
          <% end %>
<% end %>
</div>

<script>


    $(document).on('click', '.commentsUrl', function(e) {
            e.preventDefault();
            $.ajax({
                url: "<%= supports_show_comment_path %>",
                type: "GET",
                data: {issue_id: $(this).data("id")}
            });
            $.ajax({
                url: "<%= comments_readed_path %>",
                type: "GET",
                data: {issue_id: $(this).data("id")}
            })
        });

</script>

app/views/supports/_comments_tables.html.erb
<div class="row">
    <div class="col-3">
      <div id="issuesLastComment">
        <%= render 'supports/comments_issues_list', issues: @issues %>
      </div>
    </div>
    <div class="col-7">
      <div id="showComment">

      </div>
    </div>

    <div class="col-2">
      <div id="showUser">

      </div>
    </div>

</div>



app/views/supports/_issues_list.html.erb
<div class="row" style="margin-top: 35px; margin-left: 5px; margin-right: 5px;">

  <div class="col-8">
    <div class="row">
      <div class="col-4 droptrue" id="В работе">
        <h5 class="nodrag">В работе:</h5>
        <%issues_in_work(issues).each do |issue| %>

            <a data-priority="<%=issue.priority%>" data-id="<%=issue.id%>" href="URL" class="card cardUrl" style="border-top: 0;margin-top: 10px">
              <div class="span4">
                <img class="img-right" src="<%=issue.author.avatar.url%>" height="34" width="34"/>
                <p class="mb-0 pb-0">Задача#<%=issue.id%></p>
                <p><%=l(issue.created_at, format: "%e %b %Y %H:%M")%></p>
              </div>
              <div class="mx-auto">
                <div id="circle<%=issue.id%>">
                  <div class="ggt" id="timer<%=issue.id%>">
                    00:00:00
                  </div>
                </div>
              </div>
              <p class="mb-0 pb-0"><%=issue.category.name%></p>
              <span style="padding-top: 5px"><%=issue.subject%></span>
            </a>

            <script>
                var timer<%=issue.id%> = new easytimer.Timer();
                timer<%=issue.id%>.start({startValues: {seconds: <%=((Time.now - issue.open_at)-check_delayed(issue)).round%>}});
                $(timer<%=issue.id%>).on('secondsUpdated', function(e) {
                    $('#timer<%=issue.id%>').html(timer<%=issue.id%>.getTimeValues().toString());

                });


                console.log('delayed')
                console.log(<%=check_delayed(issue)%>)
                console.log('-------')


                var timeInMs = <%=Time.now.to_f * 1000%>;
                var open_at = <%=issue.open_at.to_f * 1000%>;
                var minutes = timeInMs - open_at;
                var pt = <%=issue.category.permissible_time * 60000%>;
                var res = minutes / pt ;
                localStorage.setItem('res<%=issue.id%>', res);

                /*изменить 5 чтобы уменьшить процент на котором обращается в контроллер*/
                var step = (3 / 100) * pt;

                var circle<%=issue.id%> = $('#circle<%=issue.id%>').circleProgress({
                    value: res,
                    size: 115,
                    /*fill: { gradient: ["red", "orange"]}*/
                    fill: { gradient: res < 0.85 ? ["#28afd0", "#5ed84f"] : ["red", "orange"]}
                }).on('circle-animation-start', function(event, progress) {
                    $(this).find('.ggt').html($('#timer<%=issue.id%>'));
                });

                console.log(res)

                setInterval(function(){
                    $.ajax({
                        url: "<%= find_issue_path %>",
                        type: "GET",
                        data: {id: <%=issue.id%>}
                    }).done(function(response) {

                        var timeInMs = Date.now();
                        var minutes = timeInMs - response.issue.open_at;
                        var res = minutes / (response.issue.pt * 60000) ;
                        localStorage.setItem('res<%=issue.id%>', res);
                        circle<%=issue.id%>.circleProgress('value', res);
                    });
                }, step);
            </script>
        <% end %>
      </div>

      <div class="col-4 droptrue" id="Отложена">
        <h5 class="nodrag">Отложены:</h5>
        <%issues_in_later(issues).each do |issue| %>

            <a data-priority="<%=issue.priority%>" data-id="<%=issue.id%>" href="URL" class="card cardUrl" style="border-top: 0; margin-top: 10px">
              <div class="span4">
                <img class="img-right" src="<%=issue.owner.avatar.url%>" height="34" width="34"/>
                <p class="mb-0 pb-0">Задача#<%=issue.id%></p>
                <p><%=issue.subject%></p>
              </div>
              <div class="mx-auto">
                <div id="circle<%=issue.id%>">
                  <div class="ggt">
                    <%= Time.at((Time.now - issue.open_at).round).utc.strftime("%H:%M:%S")%>
                  </div>
                </div>
              </div>
              <span style="padding-top: 5px"><%=issue.category.name%></span>
            </a>
            <script>

                var res = localStorage.getItem('res<%=issue.id%>');
                var circle<%=issue.id%> = $('#circle<%=issue.id%>').circleProgress({
                    value: res,
                    size: 115,
                    /*fill: { gradient: ["red", "orange"]}*/
                    fill: { gradient: res < 0.85 ? ["#28afd0", "#5ed84f"] : ["red", "orange"]}
                }).on('circle-animation-start', function(event, progress) {
                    $(this).find('.ggt').html('<%= Time.at((Time.now - issue.open_at).round).utc.strftime("%H:%M:%S")%>');
                });

            </script>

        <% end %>
      </div>

      <div class="col-4 droptrue cancel" id="Выполнена">
        <h5 class="nodrag">Выполнены:</h5>
        <%issues_in_done(issues).each do |issue| %>

            <a data-priority="<%=issue.priority%>" data-id="<%=issue.id%>" href="URL"
               class="card cardUrl nodrag" style="border-top: 0; margin-top: 10px">
              <div class="span4">
                <img class="img-right" src="<%=issue.owner.avatar.url%>" height="34" width="34"/>
                <p class="mb-0 pb-0">Задача#<%=issue.id%></p>
                <p><%=issue.subject%></p>
              </div>
              <div id="result<%=issue.id%>">

              </div>
              <span style="padding-top: 5px"><%=issue.category.name%></span>
            </a>
            <script>

                var timeInMs = <%=get_work_time(issue).to_f * 1000%>;
                var open_at = <%=get_done_time(issue).to_f * 1000%>;
                var minutes =  open_at - timeInMs ;
                var pt = <%=issue.category.permissible_time * 60000%>;

              if ( minutes <= pt ){
                  $('#result<%=issue.id%>').html('<div class="text-center">\n' +
                      '                  <span class="fa-stack fa-2x">\n' +
                      '                    <i class="fa fa-circle fa-stack-2x" style="color: #28a745"></i>\n' +
                      '                    <i class="fa fa-check fa-stack-1x fa-inverse" style="color: #ffffff"></i>\n' +
                      '                  </span>\n' +
                      '                  <p style="text-transform: uppercase; color: #28a745; font-weight: bold"> вовремя</p>\n' +
                      '                </div>')
              } else {
                  $('#result<%=issue.id%>').html('<div class="text-center">\n' +
                      '                <span class="fa-stack fa-2x">\n' +
                      '                   <i class="fa fa-circle fa-stack-2x" style="color: #ff3547"></i>\n' +
                      '                   <i class="fa fa-check fa-stack-1x fa-inverse" style="color: #ffffff"></i>\n' +
                      '                </span>\n' +
                      '                <p style="text-transform: uppercase; color: #ff3547; font-weight: bold">\n' +
                      '                    с опозданием\n' +
                      '                </p>\n' +
                      '              </div>')
              }
            </script>
        <% end %>
      </div>

      <%if false%>
          <div class="col-2 droptrue" id="Отменена" >
            <h5>Отмененные:</h5>
            <%issues_in_cancel(issues).each do |issue| %>

                <a data-priority="<%=issue.priority%>" data-id="<%=issue.id%>" href="URL" class="card cardUrl" style="border-top: 0; margin-top: 10px">
                  <div class="span4">
                    <img class="img-right" src="<%=issue.owner.avatar.url%>" height="34" width="34"/>
                    <p class="mb-0 pb-0">Задача#<%=issue.id%></p>
                    <p><%=issue.subject%></p>
                  </div>
                  <div class="mx-auto">
                    <span style="font-size: 2.28rem">50:53</span>
                  </div>
                  <span style="padding-top: 5px"><%=issue.category.name%></span>
                </a>


            <% end %>
          </div>
      <% end %>
    </div>
  </div>

  <div class="col-4">
    <div class="card card-image-empty" style="border-top: 0; height: 79.7vh; position: -webkit-sticky;
        position: sticky;
        top: 6.10rem;">

      <div class="card-header real-blue">
        <h5>Панель управления</h5>
        <span style="color: rgba(255,255,255,.62); font-size: .875rem;">Выберите заявку для отображения</span>
      </div>

      <div id="showPanel" style="overflow-y: auto; overflow-x: hidden">

        <h4 class="text-center" style="margin-top: 30vh">выберите задачу</h4>

      </div>
    </div>
  </div>
</div>

<script>

    $( function() {
        $( "div.droptrue" ).sortable({
            connectWith: "div.droptrue",
            cancel:'.nodrag',
            scroll: false,
            /*placeholder: "highlight",*/
            start: function (event, ui) {
                ui.placeholder.height(ui.item.height());
                ui.placeholder.css('visibility', 'visible');
            },
            stop: function (event, ui) {
               /* console.log(ui.item.parent().attr('id'))*/
                if ($(this).attr('id') != ui.item.parent().attr('id')) {

                    $.ajax({
                        url: "<%= supports_update_issue_status_path %>",
                        type: "GET",
                        data: {issue_id: ui.item.data('id'), status: ui.item.parent().attr('id')}
                    })
                }


            }
        }).disableSelection();
    } );

    $(".cardUrl").each(function() {
         if ($(this).data('priority') == 'Низкий'){
            $(this).css('border-left', '4px solid #007bff')
         }else if ($(this).data('priority') == 'Обычный'){
             $(this).css('border-left', '4px solid #28a745')
         }else if ($(this).data('priority') == 'Высокий'){
             $(this).css('border-left', '4px solid #fb3')
         }else if ($(this).data('priority') == 'Немедленный'){
             $(this).css('border-left', '4px solid #ff3547')
         }
        $(this).on('click', function(e) {
            e.preventDefault();
            $.ajax({
                url: "<%= supports_show_panel_path %>",
                type: "GET",
                data: {issue_id: $(this).data("id")}
            })
        });
    });
</script>

app/views/supports/_show_comment.html.erb
<div style="background: grey; height: 48vh; overflow-y: auto" id="alwaysBottom">
  <div id="comments">
    <%= render 'comments/comments', comments: issue.comments %>
  </div>
</div>
<div style="height: 10vh">


  <%= form_tag create_comment_path, method: :post, remote: true do %>
      <%= text_area_tag(:body, nil, class: 'form-control', rows: 3, id:'body', style: 'resize: none;')%>
      <%= hidden_field_tag :issue_id, issue.id %>
      <%= submit_tag 'Написать', :class => 'btn custom-button-blue mt-2', id: 'submitBtn' %>
  <% end %>

  <%= subscribe_to "/comments/#{issue.id}" %>
</div>

app/views/supports/_show_panel.html.erb
<br>
<span style="font-size: 14px; padding-left: 5px;"><b>Описание:</b></span>

<table class="table table-sm table-borderless" style="margin-top: 3px">
  <tbody>
  <tr>
    <td class="w-25 text-secondary">Номер:</td>
    <td class="w-75"><%=issue.id%></td>
  </tr>
  <tr>
    <td class="text-secondary">Тема:</td>
    <td><%=issue.subject%></td>
  </tr>
  <tr>
    <td class="text-secondary">Категория:</td>
    <td><%=issue.category.name%></td>
  </tr>
  <tr>
    <td class="text-secondary">Описание:</td>
    <td class="bodyText">

      <% if issue.body %>
          <%=issue.body%>
      <% else %>
          Нету
      <% end %>

    </td>
  </tr>
  <tr>
    <td class="text-secondary">Статус:</td>
    <td>

      <% if issue.status == 'В работе'%>
          <span class="badge badge-upper badge-pill badge-primary"><%=issue.status%></span>
      <% elsif issue.status == 'Отложена' %>
          <span class="badge badge-upper badge-pill badge-warning"><%=issue.status%></span>
      <% elsif issue.status == 'Отменена' %>
          <span class="badge badge-upper badge-pill badge-danger"><%=issue.status%></span>
      <% elsif issue.status == 'Выполнена' %>
          <span class="badge badge-upper badge-pill badge-success"><%=issue.status%></span>
      <% end %>
    </td>
  </tr>
  <tr>
    <td class="text-secondary">Приоритет:</td>
    <td>
      <select id="priority" name="category" style="width:80%">
        <option></option>
        <option value="Низкий">Низкий</option>
        <option value="Обычный">Обычный</option>
        <option value="Высокий">Высокий</option>
        <option value="Немедленный">Немедленный</option>
      </select>
    </td>
  </tr>
  <tr>
    <td class="text-secondary">Тип заявки:</td>
    <td>
      <select id="classification" name="category" style="width:80%">
        <option></option>
        <option value="Запрос на обслуживание">Запрос на обслуживание</option>
        <option value="Инцидент">Инцидент</option>
        <option value="Проблема">Проблема</option>
        <option value="Ремонтно-профилактические работы">Ремонтно-профилактические работы</option>
        <option value="Консультация">Консультация</option>
      </select>
    </td>
  </tr>
  </tbody>
</table>

<span style="font-size: 14px; padding-left: 5px"><b>Люди:</b></span>

<table class="table table-sm table-borderless" style="margin-top: 3px">
  <tbody>
  <tr>
    <td class="w-25 text-secondary">Создал:</td>
    <td class="w-75"><%=issue.author%></td>
  </tr>
  <tr>
    <td class="text-secondary">Владелец:</td>
    <td><%=issue.owner%></td>
  </tr>
  </tbody>
</table>

<span style="font-size: 14px; padding-left: 5px"><b>Время:</b></span>

<table class="table table-sm table-borderless" style="margin-top: 3px">
  <tbody>
  <tr>
    <td class="w-25 text-secondary">Создана:</td>
    <td class="w-75"><%=l(issue.created_at, format: "%e %b %Y %H:%M")%></td>
  </tr>
  <tr>
    <td class="text-secondary">Взята:</td>
    <td><%=l(issue.open_at, format: "%e %b %Y %H:%M")%></td>
  </tr>
  </tbody>
</table>


    <% if issue.status == 'В работе' %>


      <%= link_to to_later_path(id: issue.id), remote: :true, class: 'btn btn-sm custom-button-yellow' do %>
          Отложить
      <% end %>

      <%= link_to to_close_path(id: issue.id), remote: :true, class: 'btn btn-sm custom-button-green' do %>
          Выполнена
      <% end %>

      <%= link_to to_cancel_path(id: issue.id), remote: :true, class: 'btn btn-sm custom-button-red' do %>
          Отказ
      <% end %>



    <% elsif issue.status == 'Отложена' %>

        <%= link_to to_work_path(id: issue.id), remote: :true, class: 'btn btn-sm custom-button-blue' do %>
            В работу
        <% end %>

        <%= link_to to_close_path(id: issue.id), remote: :true, class: 'btn btn-sm custom-button-green' do %>
            Выполнена
        <% end %>
        <%= link_to to_cancel_path(id: issue.id), remote: :true, class: 'btn btn-sm custom-button-red' do %>
            Отказ
        <% end %>

    <% end %>





<script>

    var priority = $( "#priority" );
    var classification = $( "#classification" );

    priority.select2({
        language: "ru-RU",
        minimumResultsForSearch: -1,
        placeholder: "<%=issue.priority%>",
        allowClear: true

    });

    priority.on('select2:select', function (e) {
        var data = e.params.data;
        $.ajax({
            url: "<%= supports_update_issue_priority_path %>",
            type: "GET",
            data: {issue_id: <%=issue.id%>, priority: data.text}
        })
    });

    classification.select2({
        language: "ru-RU",
        minimumResultsForSearch: -1,
        placeholder: "<%=issue.classification ? issue.classification : 'Нету'%>",
        allowClear: true

    });

    classification.on('select2:select', function (e) {
        var data = e.params.data;
        $.ajax({
            url: "<%= supports_update_issue_classification_path %>",
            type: "GET",
            data: {issue_id: <%=issue.id%>, classification: data.text}
        })
    });

    $('.bodyText').each(function () {
        str = $(this).text();
        html = $.parseHTML(str);
        $(this).html(html)
    })
</script>

app/views/supports/_show_user.html.erb
<div>
  <p>ФИО:</p>
  <p>Должность:</p>
  <p>Телефон:</p>
  <p>email:</p>

  <p>Заявок открыто:</p>

  ...
</div>

app/views/supports/index.html.erb
<div class="wrapper">

  <%= render 'layouts/left_navbar', issues: @issues%>
  <!-- Page Content  -->
  <div id="content" style="overflow-y: scroll; width: 100%;">
    <%= render 'layouts/navbar' %>

    <div class="container-fluid" >

      <% if false %>
      <h6 style="margin-top: 20px">У вас <%=current_user.owned_issues.count%> заявок</h6>
      <% end %>

      <div class="row" style="display: none"></div>

      <div class="row" style="margin-top: 0; margin-left: 5px; margin-right: 5px;">
        <div class="col-12">
          <div class="card" style="border-top: 0; margin-top: 50px; height: 76vh">
            <div id="issues" style="max-width: 100%">
              <%= render 'supports/all_issues', issues: @issues, response_time: @response_time %>
            </div>

          </div>
        </div>
      </div>

    </div>

  </div>

</div>

<script>
    $('#sidebar').addClass('active');
</script>
<%= subscribe_to "/issues/all/#{current_user.id}" %>

app/views/supports/issues.html.erb
<div class="wrapper">

  <%= render 'layouts/left_navbar', issues: @issues%>
  <!-- Page Content  -->
  <div id="content" style="overflow-y: scroll; width: 100%; padding-bottom: 20px;">
    <%= render 'layouts/navbar' %>

    <div class="container-fluid" >
      <div id="issuesList">
        <%= render 'supports/issues_list', issues: @issues%>
      </div>
    </div>

  </div>

</div>

<script>
    $('#sidebar').addClass('active');

</script>

app/views/supports/show_comment.js.erb
$('#showComment').html("<%= j render(:partial => '/supports/show_comment', :locals => {issue: @issue}) %>")
$('#showUser').html("<%= j render(:partial => '/supports/show_user', :locals => {issue: @issue}) %>")


app/views/supports/show_panel.js.erb
$('#showPanel').html("<%= j render(:partial => '/supports/show_panel', :locals => {issue: @issue}) %>")

app/views/supports/update_issue_classification.js.erb
$.amaran({
    'theme'     :'awesome ok',
    'content'   :{
        title:'Внимание!',
        message:'Заявка<%=@issue.id%> обновлена',
        info:'',
        icon:'fa fa-check-square-o'
    },
    'position'  :'bottom right',
    'outEffect' :'slideBottom'
});

$('#issuesList').html("<%= j render(:partial => '/supports/issues_list', :locals => {issues: @issues}) %>")
$('#showPanel').html("<%= j render(:partial => '/supports/show_panel', :locals => {issue: @issue}) %>")

app/views/supports/update_issue_priority.js.erb
$.amaran({
    'theme'     :'awesome ok',
    'content'   :{
        title:'Внимание!',
        message:'Заявка<%=@issue.id%> обновлена',
        info:'',
        icon:'fa fa-check-square-o'
    },
    'position'  :'bottom right',
    'outEffect' :'slideBottom'
});

$('#issuesList').html("<%= j render(:partial => '/supports/issues_list', :locals => {issues: @issues}) %>")
$('#showPanel').html("<%= j render(:partial => '/supports/show_panel', :locals => {issue: @issue}) %>")