config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    root to: "devise/sessions#new"
  end

  get 'users/main' => 'users#index'
  get 'user' => 'users#show'
  get 'users/all' => 'users#all'
  post 'update_user' => 'users#update'

  get 'create_issue' => 'issues#create'
  post 'create_issue' => 'issues#create'

  get 'issue' => 'issues#show'

  get 'to_work' => 'issues#to_work'
  get 'to_later' => 'issues#to_later'
  get 'to_cancel' => 'issues#to_cancel'
  get 'to_close' => 'issues#to_close'

  get 'supports/main' => 'supports#index'
  get 'supports/issues' => 'supports#issues'
  get 'supports/dashboard' => 'supports#dashboard'

  get 'supports/update_issue_status' => 'supports#update_issue_status'
  get 'supports/update_issue_priority' => 'supports#update_issue_priority'
  get 'supports/update_issue_classification' => 'supports#update_issue_classification'
  get 'find_issue' => 'supports#find_issue'

  get 'supports/show_panel' => 'supports#show_panel'
  get 'supports/show_comment' => 'supports#show_comment'
  get 'supports/comments' => 'supports#comments'

  get 'admins/categories' => 'admins#categories'
  get 'admins/response_time' => 'admins#response_time'
  post 'set_response_time' => 'admins#set_response_time'

  post 'categories_create' => 'categories#create'
  post 'categories_update' => 'categories#update'
  get 'categories_destroy' => 'categories#destroy'

  get 'create_comment' => 'comments#create_comment'
  post 'create_comment' => 'comments#create_comment'
  get 'comments_readed' => 'comments#readed'
  get 'count_unread' => 'comments#count_unread'
  get 'count_specific_unread' => 'comments#count_specific_unread'

  get 'test' => 'supports#test'

  post 'create_attachment' => 'attachments#create'

  get 'user_notifications' => 'notifications#user_notifications'
  get 'mark_as_readed' => 'notifications#mark_as_readed'

end

app/views/layouts/_left_navbar.html.erb
<!-- Sidebar  -->
<nav id="sidebar">
  <div class="sidebar-header">
    <h3> Post<b>Desk</b></h3>
    <strong>PD</strong>
  </div>

  <ul class="list-unstyled components">

    <li class="user-link">

      <a href="#userSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
        <img src="<%=current_user.avatar.url %>" alt="user avatar" height="42" width="42">
        <span style="padding-left: 15px"><%= current_user.username %></span>
      </a>

      <ul class="collapse list-unstyled" id="userSubmenu">
        <li>
          <a href="#">Page 1</a>
        </li>
        <li>
          <a href="#">Page 2</a>
        </li>
        <li>
          <a href="#">Page 3</a>
        </li>
      </ul>
    </li>

    <% if current_user.group == 'user'%>
        <li class="<%= 'active' if current_page?(users_main_path) %>">
          <%= link_to users_main_path, method: :get do %>
              <i class="fa fa-home"></i>
              <span>Домой</span>
          <% end %>
        </li>
    <% end %>


    <% if current_user.group == 'support'%>

        <li class="<%= 'active' if current_page?(supports_dashboard_path) %>">
          <%= link_to supports_dashboard_path, method: :get do %>
              <i class="fa fa-tachometer"></i>
              <span>Дашборд</span>
          <% end %>
        </li>

        <li class="<%= 'active' if current_page?(supports_main_path) %>">
          <%= link_to supports_main_path, method: :get do %>
              <i class="fa fa-tasks"></i>
              <span>Все заявки</span>
          <% end %>
        </li>
        <li class="<%= 'active' if current_page?(supports_issues_path) %>">
          <%= link_to supports_issues_path, method: :get do %>
              <i class="fa fa-tasks"></i>
              <span>Мои заявки</span>
          <% end %>
        </li>
        <li class="<%= 'active' if current_page?(supports_comments_path) %>">
          <%= link_to supports_comments_path, method: :get do %>
              <i class="fa fa-comments"></i>
              <span>Комментарии</span>
          <% end %>
        </li>
        <li class="<%= 'active' if current_page?(users_all_path) %>">
          <%= link_to users_all_path, method: :get do %>
              <i class="fa fa-user"></i>
              <span>Пользователи</span>
          <% end %>
        </li>
    <% end %>

    <% if current_user.group == 'admin'%>
        <li class="<%= 'active' if current_page?(supports_dashboard_path) %>">
          <%= link_to supports_dashboard_path, method: :get do %>
              <i class="fa fa-tachometer"></i>
              <span>Дашборд</span>
          <% end %>
        </li>

        <li class="<%= 'active' if current_page?(supports_main_path) %>">
          <%= link_to supports_main_path, method: :get do %>
              <i class="fa fa-tasks"></i>
              <span>Все заявки</span>
          <% end %>
        </li>
        <li class="<%= 'active' if current_page?(supports_issues_path) %>">
          <%= link_to supports_issues_path, method: :get do %>
              <i class="fa fa-tasks"></i>
              <span>Мои заявки</span>
          <% end %>
        </li>
        <li class="<%= 'active' if current_page?(supports_comments_path) %>">
          <%= link_to supports_comments_path, method: :get do %>
              <i class="fa fa-comments"></i>
              <span>Комментарии</span>
          <% end %>
        </li>
        <li class="<%= 'active' if current_page?(users_all_path) %>">
          <%= link_to users_all_path, method: :get do %>
              <i class="fa fa-user"></i>
              <span>Пользователи</span>
          <% end %>
        </li>

        <li>
        <%= link_to admins_categories_path do %>
            <i class="fa fa-eye"></i>
            <span>Категории</span>
        <% end %>
        </li>
        <li>
          <%= link_to admins_response_time_path do %>
              <i class="fa fa-clock-o"></i>
              <span>Время реагирования</span>
          <% end %>
        </li>
    <% end %>
  </ul>
</nav>

<% if current_user.group == 'support' || current_user.group == 'admin' %>
    <%= subscribe_to "/issues/all" %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background: transparent !important;">
  <div class="container-fluid">

    <button type="button" id="sidebarCollapse" class="btn btn-toggle">
      <i id="toggleIcon" class="fa fa-ellipsis-v"></i>
    </button>
    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="nav navbar-nav" style="margin-left: 50px">
        <li class="nav-item">
          <!--<a class="nav-link bread" href="#">Домой</a>-->
        </li>
      </ul>

      <ul class="nav navbar-nav ml-auto">
        <li class="nav-item dropdown no-caret">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-bell fa-lg" aria-hidden="true">
              <span class="badge badge-light" style="position: absolute;
                  top: -0.6rem; right: -0.3rem" id="unreadNotifications"></span>
            </i>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown" id="notifications">
          </div>
        </li>
        <%= subscribe_to "/notifications/#{current_user.id}" %>

        <% if current_user.group == 'support' || current_user.group == 'admin'%>
          <li class="nav-item">
            <%= link_to supports_comments_path, class: 'nav-link', id: 'navbarDropdown', method: :get,
                        style: 'position: relative' do%>
              <i class="fa fa-comments fa-lg">
                <span class="badge badge-light" style="position: absolute;
                    top: -0.6rem; right: -0.3rem" id="unreadCount"></span>
              </i>
            <% end %>
          </li>
            <%= subscribe_to "/comments/count/#{current_user.id}" %>
        <% end %>

        <li class="nav-item">
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'nav-link') %>
        </li>
        <li class="nav-item">

        </li>
      </ul>
    </div>
  </div>
</nav>




app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Postdesk</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>